sudo -u postgres psql -c "DROP DATABASE IF EXISTS paris;"
echo "DROP DB OK"
sudo -u postgres psql -c "CREATE DATABASE paris;"
echo "CREATE DB OK"
sudo -u postgres psql -d paris -f "create_table.sql"
echo "CREATE TABLES OK"
sudo -u postgres psql -d paris -c "\copy evenement(evenement, startYear, endYear, commentaire) FROM '/home/geof/projects/monuments-paris/csv/concat/evenement.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE EVENEMENT OK"
sudo -u postgres psql -d paris -c "\copy roi(wikiID, nom, dateOfBirth, placeOfBirthLabel, dateOfDeath, placeOfDeathLabel, mannersOfDeath, placeOfBurialLabel, fatherLabel, motherLabel, spouses, startTime, endTime, startYear, endYear, birthYear, deathYear) FROM '/home/geof/projects/monuments-paris/csv/concat/roi.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE ROI OK"
sudo -u postgres psql -d paris -c "\copy lieu(nom, lon, lat, inception, height, constructionYear) FROM '/home/geof/projects/monuments-paris/csv/concat/monument.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE LIEU OK"
sudo -u postgres psql -d paris -c "\copy personnage(nom, dateOfBirth, placeOfBirthLabel, dateOfDeath, placeOfDeathLabel, positions, birthYear, deathYear) FROM '/home/geof/projects/monuments-paris/csv/concat/personnage.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE PERSONNAGE OK"