sudo -u postgres psql -c "DROP DATABASE IF EXISTS paris;"
echo "DROP DB OK"
sudo -u postgres psql -c "CREATE DATABASE paris ENCODING = 'UTF-8' TEMPLATE=TEMPLATE0;"
echo "CREATE DB OK"
sudo -u postgres psql -d paris -f "create_table.sql"
echo "CREATE TABLES OK"
sudo -u postgres psql -d paris -c "\copy evenement(evenement, startYear, endYear, commentaire, prod) FROM '/home/geof/projects/monuments-paris/csv/postgres/evenement.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE EVENEMENT OK"
sudo -u postgres psql -d paris -c "\copy personnage(wikiID, nom, dateOfBirth, placeOfBirthLabel, dateOfDeath, placeOfDeathLabel, mannersOfDeath, placeOfBurialLabel, fatherLabel, motherLabel, spouses, startTime, endTime, startYear, endYear, birthYear, deathYear,urlImage, cat, prod) FROM '/home/geof/projects/monuments-paris/csv/postgres/personnage.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE PERSONNAGE OK"
sudo -u postgres psql -d paris -c "\copy lieu(nom, lon, lat, inception, height, constructionYear, prod) FROM '/home/geof/projects/monuments-paris/csv/postgres/lieu.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE LIEU OK"
sudo -u postgres psql -d paris -c "\copy objet(nom, startYear,endYear,urlImage,prod) FROM '/home/geof/projects/monuments-paris/csv/postgres/objet.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE OBJET OK"
sudo -u postgres psql -d paris -c "\copy user_info(pseudo) FROM '/home/geof/projects/monuments-paris/csv/postgres/user.csv' delimiter ',' csv header encoding 'UTF8';"
echo "POPULATE USER OK"